### ISSUE TITLE
Print pdf shows big Info Support logo

### ISSUE THREAD

**Issue by nicojs** [riezebosch/reveal.js-theme-infosupport#1]
I don't understand how to export a pdf. The second to last slide always seem to have a big Info Support logo.
![big infosupport logo](https://cloud.githubusercontent.com/assets/1828233/19589078/5f92a2f4-976a-11e6-9ed2-aca68e4795bd.png)

**Comment by riezebosch** [comment]
I've crafted a fix, could you try to run a `bower update` on the presentation?

**Comment by nicojs** [comment]
The logo is now in the lower left corner. Nicely crafted 👍 

However a simple bower update wasn't enought, because the version went from 0.0.2 to 0.0.3, which is a major release according to semver2. The yeoman generator gave me the dependency:

``` json
    "reveal.js-theme-infosupport": "~0.0.2"
```

I changed it locally to 

``` json
    "reveal.js-theme-infosupport": ">=0.0.2"
```

Then the bower update works like a charm

**Comment by riezebosch** [comment]
I'll have to update the generator also. There is also a dependency version conflict at the moment between reveal.js and the theme I guess.
